# Generated by Django 5.2.6 on 2025-10-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_alter_upperairsynopreport_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportedmap',
            name='map_type',
            field=models.CharField(choices=[('PNG', 'PNG'), ('SVG', 'SVG'), ('PDF', 'PDF')], max_length=50),
        ),
    ]
