"""
Management command to clear only upper air related cache.
Usage: python manage.py clear_upperair_cache
"""
from django.core.management.base import BaseCommand
from django.core.cache import cache
from django.core.cache.utils import make_template_fragment_key


class Command(BaseCommand):
    help = 'Clear only upper air related cache (observation times, available levels)'

    def add_arguments(self, parser):
        parser.add_argument(
            '--verbose',
            action='store_true',
            help='Show detailed information about cache clearing',
        )

    def handle(self, *args, **options):
        verbose = options.get('verbose', False)
        cleared_count = 0
        
        self.stdout.write('Clearing upper air cache...')
        
        # List of cache key patterns for upper air data
        # These are generated by Django's cache_page decorator
        upper_air_patterns = [
            'views.decorators.cache.cache_page',
            'upperair-observation-times',
            'available-levels',
            '200HPA',
            '500HPA', 
            '700HPA',
            '850HPA',
        ]
        
        try:
            # If cache backend supports pattern matching (like Redis)
            if hasattr(cache, 'delete_pattern'):
                for pattern in upper_air_patterns:
                    deleted = cache.delete_pattern(f'*{pattern}*')
                    if deleted:
                        cleared_count += deleted
                        if verbose:
                            self.stdout.write(f'  ✓ Cleared {deleted} keys matching: {pattern}')
            
            # If cache backend supports key iteration
            elif hasattr(cache, 'keys'):
                all_keys = cache.keys('*')
                for key in all_keys:
                    key_str = str(key)
                    if any(pattern in key_str for pattern in upper_air_patterns):
                        cache.delete(key)
                        cleared_count += 1
                        if verbose:
                            self.stdout.write(f'  ✓ Cleared key: {key_str}')
            
            # Fallback: clear entire cache if we can't be selective
            else:
                self.stdout.write(self.style.WARNING(
                    'Cache backend does not support selective clearing. '
                    'Clearing entire cache...'
                ))
                cache.clear()
                cleared_count = 1
        
        except Exception as e:
            self.stdout.write(self.style.ERROR(f'Error during cache clearing: {e}'))
            self.stdout.write(self.style.WARNING('Falling back to clearing entire cache...'))
            cache.clear()
            cleared_count = 1
        
        if cleared_count > 0:
            self.stdout.write(self.style.SUCCESS(
                f'✓ Upper air cache cleared successfully! ({cleared_count} items removed)'
            ))
        else:
            self.stdout.write(self.style.WARNING('No upper air cache found or already cleared'))
        
        self.stdout.write('')
        self.stdout.write('Tip: Run "python manage.py clear_cache" to clear ALL cache')
